### Get Orders
GET http://localhost/api/orders
Accept: application/json
Content-Type: application/json


### Create Orders
POST http://localhost/api/orders
Accept: application/json
Content-Type: application/json

{
  "quantity": "10"
}
