### Get Pending Orders
GET http://localhost/api/orders
Accept: application/json
Content-Type: application/json


### Get Orders Ready
GET http://localhost/api/orders?status=ready
Accept: application/json
Content-Type: application/json


### Create N Quantity Random Orders
POST http://localhost/api/orders
Accept: application/json
Content-Type: application/json

{
  "quantity": "5"
}


### Create Order By Recipe
POST http://localhost/api/orders
Accept: application/json
Content-Type: application/json

{
  "recipe": 6
}


### Create Random Order
POST http://localhost/api/orders
Accept: application/json
Content-Type: application/json
